[Vanguard Retirement Investment Planner A/B Testing]
name = "vanguard-ab-test"
version = "0.1.0"
description = "Data Analysis on new UI"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "matplotlib>=3.9.2",
    "seaborn>=0.13.2",
    "jupyter>=1.1.1",
    "ipykernel>=6.29.5",
    "plotly>=5.24.1",
    "scipy>=1.13.1"
]